# Generated by Django 4.2.7 on 2025-04-15 18:14

from django.db import migrations
from django.utils import timezone

def fix_default_values(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Product = apps.get_model('core', 'Product')
    OrderItem = apps.get_model('core', 'OrderItem')
    
    # Update all existing records with current timestamp
    now = timezone.now()
    Category.objects.all().update(created_at=now)
    Product.objects.all().update(created_at=now)
    OrderItem.objects.all().update(created_at=now)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_is_available_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_default_values),
    ]
